jobseeker/urls.py
from django.urls import path

from jobseeker.views import *

urlpatterns = [
    path("register/",SignUpView.as_view(),name="signup"),
    path("index/",StudentIndexView.as_view(),name="indexseeker"),
    path("addprofile/",ProfileCreateView.as_view(),name="profile"),
    path("detail/<int:pk>/profile/",ProfileDetailView.as_view(),name="profiledetail"),
    path("profile/<int:pk>/change",ProfileEditView.as_view(),name="profileedit"),
    path("signout/seeker",SignoutView.as_view(),name="logout"),
    path("job/<int:pk>/detail",JobDetailView.as_view(),name="detailjob"),
    path("job/<int:pk>/apply",ApplyJobView.as_view(),name="applyjob"),
    path("application/all",ApplicationListView.as_view(),name="myapplications"),
    path("job/<int:pk>/save",JobSaveView.as_view(),name="savedjob"),
    path("job/all/save",SavedJobView.as_view(),name="jobsaveno"),

]

placementapplication/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("hr.Urls")),
    path("seeker/",include("jobseeker.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobseeker/models.py
from django.db import models

# Create your models here.

myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=200,unique=True)

    def __str__(self):
        return self.name
    
class Jobs(models.Model):
    title=models.CharField(max_length=200)
    description=models.CharField(max_length=200)
    salary=models.PositiveIntegerField()
    experience=models.PositiveIntegerField(default=0)
    created_date=models.DateTimeField(auto_now_add=True,null=True)
    last_date=models.DateField()
    vaccancies=models.PositiveIntegerField(default=1)
    poster=models.ImageField(upload_to="posterimages",null=True,blank=True)
    contact=models.CharField(max_length=200)
    qualification=models.CharField(max_length=200)
    category=models.ForeignKey(Category,on_delete=models.DO_NOTHING)
    status=models.BooleanField(default=True)
    company=models.CharField(max_length=200,null=True)
    options=(
        ("part-time","part-time"),
        ("full-time","full-time")
    )
    job_type=models.CharField(max_length=200,choices=options,default="full-time")

    def __str__(self) -> str:
        return self.title
    
    def application_count(self):
        qs=Applications.objects.filter(job=self).count()
        return qs
    
class StudentProfile(models.Model):
    qualification=models.CharField(max_length=200)
    resume=models.FileField(upload_to="resumes",null=True,blank=True)
    skills=models.CharField(max_length=200)
    age=models.PositiveIntegerField()
    options=(
        ("Male","Male"),("Female","Female"),("Others","Others")
    )
    gender=models.CharField(max_length=200,choices=options,default="Male")
    experience=models.PositiveIntegerField(default=0)
    address=models.CharField(max_length=200)
    phone=models.CharField(max_length=200)
    profile_pic=models.ImageField(upload_to="profilepics",null=True,blank=True)
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
    saved_jobs=models.ManyToManyField(Jobs,null=True,related_name="saved",blank=True)

    def __str__(self):
        return self.user.username

class Applications(models.Model):
    job=models.ForeignKey(Jobs,on_delete=models.DO_NOTHING)
    student=models.ForeignKey(User,on_delete=models.CASCADE)
    applied_date=models.DateTimeField(auto_now_add=True)
    options=(
        ("pending","pending"),("rejected","rejected"),("processing","processing"),("shortlisted","shortlisted")
    )
    status=models.CharField(max_length=200,choices=options,default="pending")

class Projects(models.Model):
    name=models.CharField(max_length=200)
    description=models.CharField(max_length=200)
    git_link=models.CharField(max_length=200)
    user=models.ForeignKey(StudentProfile,on_delete=models.DO_NOTHING)

    def __str__(self) -> str:
        return self.name




    

jobseeker/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from myapp.models import StudentProfile

class RegistrationForm(UserCreationForm):

    class Meta:
        model=User
        fields=["username","email","password1",'password2',"first_name"]



class ProfileForm(forms.ModelForm):

    class Meta:
        model=StudentProfile
        exclude=("user",)

        widgets = {
            'gender': forms.Select(attrs={"class":"form-select form-control"}),
            'qualification': forms.TextInput(attrs={"class": "form-control "}),
            'resume': forms.FileInput(attrs={"class": "form-control "}),
            'skills': forms.Textarea(attrs={"class": "form-control","row":"3"}),
            'age': forms.TextInput(attrs={"class": "form-control " }),
            'gender': forms.Select(attrs={"class": "form-select form-control "}),
            'experience': forms.TextInput(attrs={"class": "form-control "}),
            'address': forms.TextInput(attrs={"class": "form-control "}),
            'phone': forms.TextInput(attrs={"class": "form-control "}),
            'profile_pic': forms.FileInput(attrs={"class": "form-control "}),
        }
        

jobseeker/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.urls import reverse_lazy

from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator

from django.views.generic import View,CreateView,TemplateView,DetailView,UpdateView,ListView

from jobseeker.forms import RegistrationForm,ProfileForm
from myapp.models import StudentProfile,Jobs,Applications,Category

# Create your views here.


# DECRATORS ---->

def signin_required(fn):
    def wrapper(request,*args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("signin")
        else:
            return fn(request,*args, **kwargs)
    return wrapper

decs=[never_cache,signin_required]


class SignUpView(CreateView):
    template_name="jobseeker/register.html"
    form_class = RegistrationForm
    success_url=reverse_lazy("signin")

@method_decorator(decs,name="dispatch")
class SignoutView(View):
    def get(self,request,*args, **kwargs):
        logout(request)
        return redirect("signin")

@method_decorator(decs,name="dispatch")
class StudentIndexView(ListView):
    template_name="jobseeker/index.html"
    context_object_name="data"
    model=Jobs
    # def get_queryset(self):
    #     qs=Jobs.objects.all().order_by("-created_date")
    #     return qs
    
    def get_queryset(self):
        my_application=Applications.objects.filter(student=self.request.user).values_list("job",flat=True)
        # id .....
        qs=Jobs.objects.exclude(id__in=my_application).order_by("-created_date")
        
        # localhost:8000/seeker/index/?category=frontent
        
        if "category" in self.request.GET:
            category_value=self.request.GET.get("category")
            print(category_value)
            qs=qs.filter(category__name=category_value)
        return qs
    
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        qs=Category.objects.all()
        print(qs)
        context["categories"]=qs
        return context
    
@method_decorator(decs,name="dispatch")
class ProfileCreateView(CreateView):

    template_name="jobseeker/profile.html"
    form_class=ProfileForm
    success_url=reverse_lazy("indexseeker")

    def form_valid(self, form):
        form.instance.user=self.request.user

        return super().form_valid(form)
    
@method_decorator(decs,name="dispatch")
class ProfileDetailView(DetailView):
     
     template_name="jobseeker/detailprofile.html"
     context_object_name="data"

     model=StudentProfile

@method_decorator(decs,name="dispatch")
class ProfileEditView(UpdateView):
    template_name="jobseeker/profileedit.html"
    form_class=ProfileForm
    model=StudentProfile
    success_url=reverse_lazy("indexseeker")

# class JoblistView(ListView):
#     template_name="jobseeker/joblist.html"
#     context_object_name="data"
#     model=Jobs

# seeker/jobs/<int:pk>/detail
    
@method_decorator(decs,name="dispatch")
class JobDetailView(DetailView):
    
    template_name="jobseeker/jobdetail.html"
    model=Jobs
    context_object_name="data"

# seeker/jobs/<int:pk>/apply
@method_decorator(decs,name="dispatch")
class ApplyJobView(View):
    def post(self,request,*args, **kwargs):
        id=kwargs.get("pk")
        job_object=Jobs.objects.get(id=id)
        student_object=request.user
        Applications.objects.create(job =job_object,student=student_object)
        return redirect("indexseeker")

@method_decorator(decs,name="dispatch")
class ApplicationListView(ListView):
    template_name="jobseeker/applications.html"
    model=Applications
    context_object_name="data"

    def get_queryset(self):
        qs=Applications.objects.filter(student=self.request.user)
        print(qs)
        return qs

# localhost:8000/job/<int:pk>/save
@method_decorator(decs,name="dispatch")
class JobSaveView(View):
    def post(self,request,*args, **kwargs):
        id=kwargs.get("pk")
        job_object=Jobs.objects.get(id=id)
        action=request.POST.get("action") #save/unsave
        if action=="save":
            request.user.profile.saved_jobs.add(job_object)
        elif action=="unsave":
            request.user.profile.saved_jobs.remove(job_object)
        return redirect("indexseeker")

@method_decorator(decs,name="dispatch")
class SavedJobView(View):
    template_name="jobseeker/savedjob.html"
    model=StudentProfile
    def get(self,request,*args, **kwargs):
        qs=request.user.profile.saved_jobs.all()
        return render(request,self.template_name,{"data":qs})

jobseeker/templates/jobseeker/applications.html
{%extends "jobseeker/base.html"%}
{%block mainblock%}
{% load static %}
<div>

</div>
{%if form.errors%}
{{form.errors}}
{%endif%}

<div class="row">
    <div class="col-2 bg-light ">
        <div class="mt-5 mx-2">
        </div>
    </div>
    <div class="col-8 ps-4 pt-5 bg-light">
        <div class="">
            <div class="container-fluid">
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-warning" type="submit">Search</button>
                </form>
            </div>
            <hr class="border-3 w-25 d-flex justify-content-center"><br>
        </div>
        {%for application in data%}
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-3">
                    {%if application.job.poster%}
                    <div class="d-flex justify-content-center ">
                        <img src="{{application.job.poster.url}}" class="" style="width: 50%;height: fit-content;object-fit:cover;">

                    </div>
                    {%else%}
                    <div class="d-flex justify-content-center align-content-around">
                        <img src="{% static 'jobseeker/images/hiring.jpg' %}" class=""
                            style="width: 50%;height: fit-content;">
                    </div>
                    {%endif%}
                </div>
                <div class="col-md-3 ">
                    <div class="card-body">
                        <h5 class="card-title">{{application.job.title}}</h5>
                        <p class="fw-bold">{{application.job.company}}</p>
                    </div>
                </div>
                <div class="col-md-3 d-flex align-items-center justify-content-center flex-column ">
                    <div class="">
                        <p>Application : {{application.job.application_count}}</p>
                    </div>
                </div>
                <div class="col-md-3 d-flex align-items-center justify-content-center flex-column ">
                    <div class="">
                        {{application.status}}
                    </div>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
    <div class="col-2 bg-light ">
        <div class="mt-5 mx-2">
        </div>
    </div>
</div>


{%endblock%}

jobseeker/templates/jobseeker/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>link sphere</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{%static 'css/profile.css'%}">
    <link rel="stylesheet" href="{%static 'css/index.css'%}">
</head>

<body>
    <!-- nav starts -->
    <nav class="navbar sticky-top fixed-top  p-0" >
        <div class="container-fluid">

            <a href="{%url 'indexseeker' %}"><img src="{%static 'images/logojob.png' %}" alt="Logo" width="100" height="h-auto" class=""></a href="">

            <!-- search start -->
            <div class="container mt-3 w-50 mb-2">
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        <form class="d-flex">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-dark rounded-start-0" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- search end -->

            <!-- <a href="post_form.html"><i class="fa-regular fa-square-plus me-4 fs-3 text-white opacity-75"></i></a> -->

            <!-- profile dropdown start -->

            <div class="dropdown nav-item mr-lg-4 me-0 " style="margin-right: 6em;">
                <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle">
                    <!-- <b class="caret"></b> -->
                    {%if request.user.profile.profile_pic%}
                    <img class="profile-xsmall rounded-circle " src="{{request.user.profile.profile_pic.url}}" alt="Avatar"
                        style="width: 100px">
                    {%else%}
                    <img class="profile-xsmall" src="{%static 'images/profilepic.png'%}" alt="Avatar"
                        style="width: 100px;">
                    {%endif%}
                </a>
                <ul class="dropdown-menu p-2" role="menu">
                    {%if request.user.profile%}

                    <li class="nav-item">
                    <li class="nav-item">
                        <a href="{%url 'profiledetail' request.user.profile.id%}" class="nav-link scroll">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a href="{%url 'profileedit' request.user.profile.id%}" class="nav-link scroll">Edit
                            profile</a>
                    </li>
                    </li>
                    {%else%}
                    <a href="{%url 'profile'%}" class="nav-link scroll">Add profile</a>

                    {%endif%}
                    <li class="nav-item">
                        <a href="{%url 'myapplications'%}" class="nav-link scroll">Applied Job</a>
                    </li>
                    <li class="nav-item">
                        <a href="{%url 'jobsaveno'%}" class="nav-link scroll">Saved Job</a>
                    </li>
                    <div class="dropdown-divider"></div>
                    <li class="nav-item">
                        <a href="{%url 'logout'%}" class="nav-link scroll">Logout</a>
                    </li>
                </ul>
            </div>
            <a href="{%url 'logout'%}" class="fw-bolder text-black me-3 ">Logout</a>
            <!-- profile dropdown end -->


    </nav>

    <div class="container mt-3">
        {%block categoryblock%}

        {%endblock%}
    </div>

    <div class=" container d-flex flex-column justify-content-center align-items-center mt-5">
        {%block mainblock%}

        {%endblock%}
    </div>
</body>

</html>

jobseeker/templates/jobseeker/detailprofile.html
{%extends 'jobseeker/base.html'%}
{%block mainblock%}

<!-- section start -->

<div class="container d-flex justify-content-center">
    <div class="color-card card p-3 py-4 col-md-8">]]
        <div class="text-center">
            <div class="profile mr-3">
                <div class="card"> <img class="card-img-top" src="https://i.imgur.com/K7A78We.jpg" alt="Card image cap">
                    <div class="card-body little-profile text-center">
                        <div class="pro-img">
                            {%if data.profile_pic%}
                            <img src="{{data.profile_pic.url}}" class="card-img-top" alt="..." width="130"
                                class="rounded mb-2 img-thumbnail">
                            {%endif%}
                        </div>
                    </div>
                    <h1 class="mt-2 fw-bold">{{data.user}}</h1>
                    <span class="mt-1 clearfix">Android Developer</span>

                    <hr class="line">

                    <div class="media-body mb-5 text-black ">
                        <p class="small mb-4 fw-bold "> <i class="fa fa-map-marker mr-2 fw-bold "></i>Address:
                            {{data.address}}</p>
                        <p class="card-text fw-bold ">Phone: {{data.phone}}</p>
                        <p class="card-text fw-bold ">Email: {{data.user.email}}</p>
                    </div>

                    <hr class="line">


                    <div class="row mt-3 mb-3">

                        <div class="col-md-4">
                            <h5 class="fw-bold ">Experience</h5>
                            <span class="num">{{data.experience}}</span>
                        </div>
                        <div class="col-md-4">
                            <h5 class="fw-bold ">Gender</h5>
                            <span class="num">{{data.gender}}</span>
                        </div>
                        <div class="col-md-4">
                            <h5 class="fw-bold ">Qualification</h5>
                            <span class="num">{{data.qualification}}</span>
                        </div>

                    </div>
                    <h5 class="fw-bold ">Skills</h5>
                    <small class="mt-4">{{data.skills}}</small>

                    <div class="profile mt-5">

                        <div class="card-body">
                            <a href="{{data.resume.url}}" download class="card-link btn btn-dark ">Download CV</a>
                            
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

jobseeker/templates/jobseeker/index.html
{%extends 'jobseeker/base.html' %}
{%block categoryblock%}

<div class="row text-warning " >
  {% for cat in categories %}
    <div class="col-2">
      <a href="{%url 'indexseeker'%}?category={{cat.name}}" class="btn btn-outline-warning ">{{cat.name}}</a>
      <p>[{{cat.jobs_set.all.count}}-job]</p>
    </div>
    {%endfor%}
</div>

{%endblock%}

{%block mainblock%}
{%for job in data%}

<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4 d-flex justify-content-center align-items-center px-2 ">
      {%if job.poster%}
      <img src="{{job.poster.url}}" class="img-fluid rounded-start" alt="...">
      {%endif%}
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{job.title}}</h5>
        <p class="card-text">
          <i class="fa-regular fa-clock"></i> {{job.job_type}}
          <i class="fa-solid fa-sack-dollar" style="color: #3f4040;"></i> {{job.salary}}
          <i class="fa-solid fa-building" style="color: #4a4a4a;"></i> {{job.company}}

        </p>

        {% if request.user.profile %}
          <form action="{%url 'savedjob' job.id %}" method="post">
            {% csrf_token %}
            {% if job in request.user.profile.saved_jobs.all %}
            <button type="submit" name="action" value="unsave" class="btn">
              <i class="fa-solid fa-bookmark"> </i>
            </button>
            {%else%}
            <button type="submit" name="action" value="save" class="btn">
              <i class="fa-regular fa-bookmark"> </i>
            </button>
            {%endif%}
          </form>
          {% endif %}
        <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
        <div>
          <a href="{%url 'detailjob' job.id%}" class="btn btn-dark ">View More</a>
        </div>

      </div>
    </div>
  </div>
</div>

{%endfor%}

{%endblock%}

jobseeker/templates/jobseeker/jobdetail.html
{%extends 'jobseeker/base.html'%}
{%block mainblock%}

<div class="card mt-5" style="width:80%" >
    <div class="row">
        <div class="col-4 d-flex align-items-center">
            {%if data.poster%}
            <img src="{{data.poster.url}}" class="rounded-start" alt="..." style="width: 100%;">
            {%endif%}
        </div>
        <div class="col-8">

            <div class="card-body">
                <h5 class="card-title fw-bolder">{{data.title}}</h5>
                <p class="card-text">
                    {{data.description}}
                </p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">salary : {{data.salary}}</li>
                <li class="list-group-item">Experience :{{data.experience}}</li>
                <li class="list-group-item">Last Date{{data.last_date}}</li>
                <li class="list-group-item">Vaccancies{{data.vaccancies}}</li>
                <li class="list-group-item">Contact{{data.contact}}</li>
                <li class="list-group-item">Qualification:{{data.qualification}}</li>
                <li class="list-group-item">category:{{data.category}}</li>
                <li class="list-group-item">company:{{data.company}}</li>
                <li class="list-group-item">type:{{data.job_type}}</li>
            </ul>
            <div class="card-body d-flex justify-content-center">
                <form action="{%url 'applyjob' data.id%}" method="post">
                    {%csrf_token%}
                        <button type="submit" class="btn btn-warning ">Apply</button>
                </form>
            </div>
        </div>
    </div>
</div>
{%endblock%}

jobseeker/templates/jobseeker/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Jobs</title>

        <link rel="stylesheet" href="style.css">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
                integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
                crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
                integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
                crossorigin="anonymous" referrerpolicy="no-referrer" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
                crossorigin="anonymous"></script>
</head>

<body>
        <div class="overflow-x-hidden bg-danger  ">
                {% if form.errors%}
                {{form.errors}}
                {%endif%}
                <div class="container d-flex justify-content-around">
                        <form action="" method="post" class="bg-white m-5 p-5 w-75 rounded-3" enctype="multipart/form-data">
                                {%csrf_token%}
                                <p class="fw-bold fs-4 ">Profile</p>
                                <hr class="mb-5 w-25 border-4">
                                <div class=" row">
                                        <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class=""
                                                        for="">Qualification
                                                        :</label><input type="text" name="qualification" class="form-control">
                                        </div>
        
                                        <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label for="">Gender :</label>
                                                {{form.gender}}
                                        </div>
        
                                        <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Profile
                                                        Picture
                                                        :</label><input type="file" name="profile_pic" class="form-control">
                                        </div>
                                        <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Resume
                                                        :</label><input type="file" name="resume" class="form-control"></div>
                                        <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Phone
                                                        :</label><input type="number" name="phone" class="form-control"></div>
                                        <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Experience
                                                        :</label><input type="text" name="experience" class="form-control">
                                        </div>
                                        <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Age
                                                        :</label><input type="text" name="age" class="form-control"></div>
                                        <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Skills
                                                        :</label><textarea name="skills" class="form-control"></textarea></div>
                                        <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Address
                                                        :</label><textarea name="address" class="form-control"></textarea></div>
                                        <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4"><input type="text" name="user"
                                                        value="" hidden></div>
                                        <div class="text-center">
                                                <button class="btn btn-dark mt-4 mb-4 w-50">Submit</button>
                                                <br>
                                        </div>
                                </div>
                        </form>
                </div>
        </div>
</body>

</html>

jobseeker/templates/jobseeker/profileedit.html
{%extends "jobseeker/base.html"%}
{%block mainblock%}

<div class="container d-flex justify-content-around">
        <form action="" method="post" class="bg-white m-5 p-5 rounded-3" enctype="multipart/form-data">
                {%csrf_token%}
                <p class="fw-bold fs-4 ">Profile</p>
                <hr class="mb-5 w-25 border-4">
                <div class=" row">
                        {{form.as_p}}
                        
                        <div class="text-center">
                                <button class="btn btn-dark mt-4 mb-4 w-50">Submit</button>
                                <br>

                        </div>


                </div>
        </form>
</div>

{%endblock%}